"""add_assumption_sets

Revision ID: 44f56071e50e
Revises: 92d97d3372e8
Create Date: 2026-07-27 16:01:54.885071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44f56071e50e'
down_revision: Union[str, Sequence[str], None] = '92d97d3372e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_tenant_code', ['tenant_id', 'code'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_type', sa.String(length=16), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_tenant_due', ['tenant_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_invoices_tenant_status', ['tenant_id', 'status'], unique=False)

    op.create_table('assumption_sets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assumption_sets', schema=None) as batch_op:
        batch_op.create_index('ix_assumption_sets_tenant', ['tenant_id'], unique=False)

    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('current_assets', sa.Float(), nullable=False),
    sa.Column('non_current_assets', sa.Float(), nullable=False),
    sa.Column('total_liabilities', sa.Float(), nullable=False),
    sa.Column('current_liabilities', sa.Float(), nullable=False),
    sa.Column('non_current_liabilities', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('retained_earnings', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_sheets_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_sheets_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_balance_sheets_tenant_period', ['tenant_id', 'period_end'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_budgets_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('ix_budgets_tenant_year', ['tenant_id', 'year'], unique=False)

    op.create_table('cash_flow_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('operating_activities', sa.Float(), nullable=False),
    sa.Column('investing_activities', sa.Float(), nullable=False),
    sa.Column('financing_activities', sa.Float(), nullable=False),
    sa.Column('net_cash_change', sa.Float(), nullable=False),
    sa.Column('beginning_cash', sa.Float(), nullable=False),
    sa.Column('ending_cash', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_flow_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_flow_statements_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flow_statements_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_cash_flow_statements_tenant_period', ['tenant_id', 'period_end'], unique=False)

    op.create_table('income_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('operating_cost', sa.Float(), nullable=False),
    sa.Column('gross_profit', sa.Float(), nullable=False),
    sa.Column('operating_expenses', sa.Float(), nullable=False),
    sa.Column('operating_income', sa.Float(), nullable=False),
    sa.Column('net_income', sa.Float(), nullable=False),
    sa.Column('eps', sa.Float(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_statements_period_end'), ['period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_statements_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_income_statements_tenant_period', ['tenant_id', 'period_end'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index('ix_journal_entries_tenant_account', ['tenant_id', 'account_id'], unique=False)
        batch_op.create_index('ix_journal_entries_tenant_date', ['tenant_id', 'entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.create_index('ix_budget_items_budget', ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_items_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_items_tenant_id'))
        batch_op.drop_index('ix_budget_items_budget')

    op.drop_table('budget_items')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_tenant_id'))
        batch_op.drop_index('ix_journal_entries_tenant_date')
        batch_op.drop_index('ix_journal_entries_tenant_account')
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('income_statements', schema=None) as batch_op:
        batch_op.drop_index('ix_income_statements_tenant_period')
        batch_op.drop_index(batch_op.f('ix_income_statements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_income_statements_period_end'))

    op.drop_table('income_statements')
    with op.batch_alter_table('cash_flow_statements', schema=None) as batch_op:
        batch_op.drop_index('ix_cash_flow_statements_tenant_period')
        batch_op.drop_index(batch_op.f('ix_cash_flow_statements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cash_flow_statements_period_end'))

    op.drop_table('cash_flow_statements')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('ix_budgets_tenant_year')
        batch_op.drop_index('ix_budgets_tenant_status')
        batch_op.drop_index(batch_op.f('ix_budgets_tenant_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('balance_sheets', schema=None) as batch_op:
        batch_op.drop_index('ix_balance_sheets_tenant_period')
        batch_op.drop_index(batch_op.f('ix_balance_sheets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_balance_sheets_period_end'))

    op.drop_table('balance_sheets')
    with op.batch_alter_table('assumption_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_assumption_sets_tenant')

    op.drop_table('assumption_sets')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_tenant_status')
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index('ix_invoices_tenant_due')

    op.drop_table('invoices')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_tenant_id'))
        batch_op.drop_index('ix_accounts_tenant_code')

    op.drop_table('accounts')
    # ### end Alembic commands ###
