"""initial_schema_all_25_models

Revision ID: 92d97d3372e8
Revises: 
Create Date: 2026-07-27 01:42:13.179764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d97d3372e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_name', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_server_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('env_vars', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_connected_at', sa.String(length=64), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_server_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_configs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_mcp_tenant_active', ['tenant_id', 'is_active'], unique=False)

    op.create_table('prompt_few_shot_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_key', sa.String(length=128), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_few_shot_examples', schema=None) as batch_op:
        batch_op.create_index('ix_few_shot_tenant_key', ['tenant_id', 'prompt_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_few_shot_examples_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('runtime_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runtime_logs', schema=None) as batch_op:
        batch_op.create_index('ix_runtime_logs_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_runtime_logs_source', ['source'], unique=False)
        batch_op.create_index('ix_runtime_logs_tenant_cat', ['tenant_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runtime_logs_user_id'), ['user_id'], unique=False)

    op.create_table('sandbox_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sandbox_configs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_sandbox_tenant_type', ['tenant_id', 'config_type'], unique=False)

    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index('ix_tool_tenant_builtin', ['tenant_id', 'is_builtin'], unique=False)
        batch_op.create_index('ix_tool_tenant_type', ['tenant_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tools_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_category', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['financial_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_prompt_tenant_type', ['tenant_id', 'template_type'], unique=False)

    op.create_table('report_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('at_hour', sa.Integer(), nullable=False),
    sa.Column('at_minute', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('export_format', sa.String(length=16), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_report_id', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_subscriptions_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('summary_template', sa.Text(), nullable=False),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('content_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sandbox_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('trigger_source', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['sandbox_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sandbox_executions', schema=None) as batch_op:
        batch_op.create_index('ix_sandbox_exec_created', ['created_at'], unique=False)
        batch_op.create_index('ix_sandbox_exec_tenant_config', ['tenant_id', 'config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_executions_config_id'), ['config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sandbox_executions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_ab_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_key', sa.String(length=128), nullable=False),
    sa.Column('variant_a_id', sa.Integer(), nullable=True),
    sa.Column('variant_b_id', sa.Integer(), nullable=True),
    sa.Column('traffic_split_b', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['variant_a_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_b_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_ab_tests', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_ab_test_tenant_key', ['tenant_id', 'prompt_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_ab_tests_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active_version', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_version_prompt_version', ['prompt_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('tool_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('ix_skill_tenant_category', ['tenant_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('prompt_ab_test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=8), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('user_feedback', sa.String(length=32), nullable=True),
    sa.Column('response_quality_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['prompt_ab_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_ab_test_results', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_ab_test_result_test_variant', ['test_id', 'variant'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_ab_test_results_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_ab_test_results_test_id'), ['test_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_ab_test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_ab_test_results_test_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_ab_test_results_session_id'))
        batch_op.drop_index('ix_prompt_ab_test_result_test_variant')

    op.drop_table('prompt_ab_test_results')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_tenant_id'))
        batch_op.drop_index('ix_skill_tenant_category')

    op.drop_table('skills')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_id'))
        batch_op.drop_index('ix_prompt_version_prompt_version')

    op.drop_table('prompt_versions')
    with op.batch_alter_table('prompt_ab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_ab_tests_tenant_id'))
        batch_op.drop_index('ix_prompt_ab_test_tenant_key')

    op.drop_table('prompt_ab_tests')
    op.drop_table('messages')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_tenant_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('sandbox_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sandbox_executions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sandbox_executions_config_id'))
        batch_op.drop_index('ix_sandbox_exec_tenant_config')
        batch_op.drop_index('ix_sandbox_exec_created')

    op.drop_table('sandbox_executions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_tenant_id'))

    op.drop_table('reports')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_tenant_id'))

    op.drop_table('report_templates')
    with op.batch_alter_table('report_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_report_subscriptions_next_run_at'))

    op.drop_table('report_subscriptions')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_tenant_type')
        batch_op.drop_index(batch_op.f('ix_prompt_templates_tenant_id'))

    op.drop_table('prompt_templates')
    op.drop_table('llm_models')
    op.drop_table('financial_accounts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_tenant_id'))

    op.drop_table('documents')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_tenant_id'))

    op.drop_table('conversations')
    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_tenant_id'))
        batch_op.drop_index('ix_tool_tenant_type')
        batch_op.drop_index('ix_tool_tenant_builtin')

    op.drop_table('tools')
    with op.batch_alter_table('sandbox_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_sandbox_tenant_type')
        batch_op.drop_index(batch_op.f('ix_sandbox_configs_tenant_id'))

    op.drop_table('sandbox_configs')
    with op.batch_alter_table('runtime_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runtime_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_runtime_logs_tenant_id'))
        batch_op.drop_index('ix_runtime_logs_tenant_cat')
        batch_op.drop_index('ix_runtime_logs_source')
        batch_op.drop_index(batch_op.f('ix_runtime_logs_session_id'))
        batch_op.drop_index('ix_runtime_logs_created')

    op.drop_table('runtime_logs')
    with op.batch_alter_table('prompt_few_shot_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_few_shot_examples_tenant_id'))
        batch_op.drop_index('ix_few_shot_tenant_key')

    op.drop_table('prompt_few_shot_examples')
    with op.batch_alter_table('mcp_server_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_mcp_tenant_active')
        batch_op.drop_index(batch_op.f('ix_mcp_server_configs_tenant_id'))

    op.drop_table('mcp_server_configs')
    op.drop_table('llm_providers')
    op.drop_table('financial_reports')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
