"""add_data_connections_agent_model_search_engine

Revision ID: b07e3d4b37b4
Revises: 44f56071e50e
Create Date: 2026-07-27 18:34:17.469125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07e3d4b37b4'
down_revision: Union[str, Sequence[str], None] = '44f56071e50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_engines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('engine_type', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=1000), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_connections_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_data_connections_tenant_type', ['tenant_id', 'connection_type'], unique=False)

    op.create_table('agent_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('tool_ids', sa.JSON(), nullable=True),
    sa.Column('skill_ids', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.create_index('ix_agent_configs_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_configs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('model_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('llm_model_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.create_index('ix_model_configs_tenant_active', ['tenant_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_configs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_configs_tenant_id'))
        batch_op.drop_index('ix_model_configs_tenant_active')

    op.drop_table('model_configs')
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_configs_tenant_id'))
        batch_op.drop_index('ix_agent_configs_tenant_active')

    op.drop_table('agent_configs')
    with op.batch_alter_table('data_connections', schema=None) as batch_op:
        batch_op.drop_index('ix_data_connections_tenant_type')
        batch_op.drop_index(batch_op.f('ix_data_connections_tenant_id'))

    op.drop_table('data_connections')
    op.drop_table('search_engines')
    # ### end Alembic commands ###
